# Generated by Django 2.2 on 2020-01-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200130_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='names',
            field=models.CharField(db_index=True, default=123, max_length=200, verbose_name='Наименоване категории во множественном числе'),
            preserve_default=False,
        ),
    ]
